name: placement
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  fl_chart: ^0.66.0  # Updated for dashboard charts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/companies.png
    - assets/icons/pending_interviews.png
    - assets/icons/placed_students.png
    - assets/icons/total_students.png
